image:
  file: .gitpod.Dockerfile

tasks:
  - init: mkdir -p build
    command: |
      cd build
      cmake .. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6
      make -j$(nproc)
  - command: |
      xpra start :100 --start-child=/workspace/QtBasics/build/QtBasics --bind-tcp=0.0.0.0:14500 --html=on
      echo "Qt GUI running on port 14500"

ports:
  - port: 14500
    onOpen: open-preview
    visibility: public
